# Generated by Django 5.2.10 on 2026-03-21 08:51

import bitpoll.base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_bitpolluser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitpolluser',
            name='timezone',
            field=models.CharField(default='Europe/Zurich', max_length=40, validators=[bitpoll.base.validators.validate_timezone]),
        ),
    ]
