# Generated by Django 5.2.10 on 2026-03-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0019_alter_choice_id_alter_choicevalue_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicevalue',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
